# Generated by Django 4.1.7 on 2023-04-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_reviews_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='game',
            name='collectibles',
            field=models.ManyToManyField(to='main_app.collectible'),
        ),
    ]
